version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: addressbook-postgres
    environment:
      POSTGRES_DB: addressbook
      POSTGRES_USER: addressbook
      POSTGRES_PASSWORD: addressbook
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: